---
version: "3.9"
services:
  wireguard:
    build:
      context: .
      dockerfile: ./docker/wireguard.Dockerfile
    container_name: wireguard
    hostname: wireguard
    environment:
      PEERS: false
    cap_add:
      - NET_ADMIN
    volumes:
      - ./conf.d/wireguard:/config
      - ./conf.d/tinyproxy:/tinyproxy
      - ./docker/start.sh:/start.sh
    ports:
      - "62820:51820/udp"
      - "8888:8888/tcp"
    # restart: unless-stopped
    # command: bash start.sh

# volumes:
#   redis_data: {}
